### ISSUE TITLE
Save Transcripts with Introns

### ISSUE THREAD

**Issue by sophec** [WillEccles/introns#7]
We should be saving a list of all transcripts that contain a given intron. This can be found by saving each transcript which contains one or more exons which border the intron.

**Comment by Gorman98** [comment]
If the donor or the acceptor is in the in the transcript include it in the transcript list

**Comment by sophec** [comment]
We can use this feature as a potential way to figure out the *actual* size of an intron. If transcript A has two exons, but does not have the one in the middle, and transcript B has 3 (the one in between the two in A), we know there are 2 introns there instead of the 1 we would find with transcript A. However, this requires much more time complexity. Need to figure out the best way to do this.
